trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Backend/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Backend/StoreHubApi/StoreHubApi.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Ensure you're using .NET 8 SDK

- script: |
    dotnet restore $(solution)
  displayName: 'Restore NuGet Packages'

- script: |
    dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build the Solution'

- script: |
    dotnet publish $(solution) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish the Application'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'deployment'
    appType: 'webApp'
    WebAppName: 'pal-store-api'
    packageForLinux: '$(Build.ArtifactStagingDirectory)'
