# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    echo $(Build.SourceBranch)
    if [[ "$(Build.SourceBranch)" == *"users"* || "$(Build.SourceBranch)" == *"main"* ]]; then
      echo "Branch name contains 'users' or 'main'."
    else
      echo "Branch name does not contain 'users' or 'main'."
      exit 1 
    fi