trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Frontend/*

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd Frontend/Palestine-Store-Hub
    npm install
    npm run build
    cd dist
    zip -r ../../palstorehub.zip .
    ls -lh ..
  displayName: 'Package the build artifacts'

- script: |
    ls -lh $(System.DefaultWorkingDirectory) # Debugging the workspace contents
  displayName: 'List Workspace Contents'
  
- publish: $(System.DefaultWorkingDirectory)/Frontend/Palestine-Store-Hub/../palstorehub.zip
  artifact: drop
  displayName: 'Publish Artifact'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'deployment'
    appType: 'webApp'
    WebAppName: 'palstorehub'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/palstorehub.zip'